module FakeData
  def self.random_city
    cities = [
      "Victorville",
      "Murfreesboro",
      "Temecula",
      "Broken Arrow",
      "San Angelo",
      "Yakima",
      "Round Rock",
      "Murrieta",
      "Palm Bay",
      "Citrus Heights",
      "Pompano Beach",
      "Orem",
      "West Palm Beach",
      "Kenosha",
      "El Cajon",
      "Mission Viejo",
      "Vacaville",
      "Daly City",
      "Portsmouth",
      "Denton",
      "Green Bay",
      "West Jordan",
      "Wichita Falls",
      "Highlands Ranch",
      "Killeen",
      "Cary",
      "Provo",
      "Costa Mesa",
      "West Covina",
      "West Valley City",
      "Olathe",
      "Ann Arbor",
      "Waco",
      "Toms River",
      "Port Saint Lucie",
      "Simi Valley",
      "Vallejo",
      "East Los Angeles",
      "El Monte",
      "Sterling Heights",
      "Alexandria",
      "Fort Collins",
      "Cape Coral",
      "Mesquite",
      "Coral Springs",
      "Escondido",
      "Sioux Falls",
      "Grand Prairie",
      "Metairie",
      "Naperville",
      "Pasadena",
      "Eugene",
      "Ponce",
      "Chattanooga",
      "Pembroke Pines",
      "Vancouver",
      "Tempe",
      "North Las Vegas",
      "Overland Park",
      "Rancho Cucamonga",
      "Moreno Valley",
      "Santa Clarita",
      "Fort Lauderdale",
      "Salt Lake City",
      "Amarillo",
      "Newport News",
      "Oxnard",
      "Sunrise Manor",
      "Mobile",
      "Winston-salem",
      "Tacoma",
      "Shreveport",
      "Spokane",
      "San Bernardino",
      "Laredo",
      "Lubbock",
      "Chula Vista",
      "Madison",
      "Hialeah",
      "Scottsdale",
      "Norfolk",
      "Plano",
      "Lexington-fayette",
      "Corpus Christi",
      "Cincinnati",
      "Pittsburgh",
      "Anaheim",
      "Wichita",
      "Colorado Springs",
      "Tulsa",
      "Virginia Beach",
      "New Orleans",
      "Albuquerque",
      "Oklahoma City",
      "Seattle",
      "Milwaukee",
      "Fort Worth",
      "San Antonio",
      "Houston"
    ]
    cities[rand(cities.length)]
  end
end